Complete Rework
GAIA-X4PLC-AAD/gx-credentials pull request #7
Opened 2023-06-24 12:00 UTC by flhps

This should be a largely functional version that could be the basis for the first open-source release. First step is testing and completing this PR.

2023-06-26 08:55 UTC, jdsika commented
@jfelixh be aware of [this branch](https://github.com/GAIA-X4PLC-AAD/gx-credentials/tree/license_and_Material_UI).

Add the license and the SPDX headers in the rework branch and delete this outdated one.

2023-06-26 16:01 UTC, flhps commented
Will do tomorrow and then it should be ready to open-source from my perspective.

2023-06-26 16:05 UTC, jdsika requested changes

2023-06-26 16:05 UTC, jdsika commented on .vscode/settings.json
> +    "prettier.prettierPath": "./node_modules/prettier"
vscode settings should not be included. "prettier" should be part of the GitHub "workflow"

2023-06-26 16:05 UTC, jdsika commented on cache/config.json
> +		"enabled": false
Where is the cache coming from? Should this be part of the gitignore?

2023-06-26 21:14 UTC, flhps commented on cache/config.json
> +		"enabled": false
This is the result of turning telemetry reporting off for Next.js. You can read on it here: https://nextjs.org/telemetry
I think it should be committed if we all agree on turning telemetry off for the project. It is somewhat pointless to only turn it off on one or two developer machines if a third one reports project metadata.

2023-06-27 09:16 UTC, flhps commented on .vscode/settings.json
> +    "prettier.prettierPath": "./node_modules/prettier"
Removed settings from tracking and added github action for prettier formatting.

2023-06-27 09:27 UTC, flhps commented
Everything should be ready now. Feel free to do further adjustments or merge, @jdsika

2023-06-27 09:29 UTC, flhps commented on .vscode/settings.json
> +    "prettier.prettierPath": "./node_modules/prettier"
We might want to add "development" to also receive prettier formatting. Right now it only is set to affect "main".

2023-06-28 06:57 UTC, jdsika approved these changes

2023-06-28 07:03 UTC, merged

2023-06-28 07:12 UTC, jdsika commented
Good job everyone!